apiVersion: v1
kind: Service
metadata:
  name: pr-agent-github-app-svc
  namespace: llms
spec:
  selector:
    app: pr-agent-github-app
  ports:
    - name: http
      port: 80
      targetPort: 3000
      nodePort: 32080
  type: NodePort
